### ISSUE TITLE
Video explicativo del taller de docker - Inglés

### ISSUE THREAD

**Issue by einjunge99** [sergioarmgpl/taller-docker#2]

**Comment by sergioarmgpl** [comment]
Do you want to work on this issue @einjunge99 ?

**Comment by sicmmar** [comment]
@sergioarmgpl I want to do it!

**Comment by sergioarmgpl** [comment]
Please refer to the issue in this repo https://github.com/sergioarmgpl/operating-systems-usac-course/issues/17
